### PR TITLE
PDF Updates & cleaned github markdown version

### PR DESCRIPTION
**Pull request by julowe**
Hello,
I started with cleaning up a few of the formatting errors and then kept going. I figured I'd contribute this back for the next people that find your repo through searching, etc. I tried to keep commits atomic. 

The earlier commits are format fixing, so if you don't want later changes let me know and I'll resubmit this from earlier commits.

Then I moved some paragraphs to the next column or page to make the PDF render better.

New additions are page numbers and sections at the bottom of pages. 

I then added another file with cleaner formatting so people can view it in a browser on Github and resize the text to read it easier - and updated the readme to reflect this.

Fixes issue #2

### CODE REVIEW

**Comment by cjue** [comment]
Thank you for your effort, especially the github / simpler version is really easy to read in the browser!

Just one thing: I still get weird rendering issues with your Homebrewery markup, both on your collab and your master branch: The main issues are in the "Nobility" and "Infamous Alleys" sections, with a partially visible third column showing up on the right side.

Could this be related to my incorrect/default page layout settings or something like that?

**Comment by julowe** [comment]
Hmmm, yes it might be page sizes. I did do quite a few iterations to fit everything as best as possible, especially on the Nobility page (text page 8) and with the Infamous Alleys note (text page 20). What settings are you using? 

For reference I am using:
Chromium Version 81.0.4044.129 (Official Build) snap (64-bit)
Destination: Save as PDF
Layout: Portrait
Paper size: letter
Margins: Default
Scale: Default 

and for future reference, this is on The Homebrewery v2.8.2

[Here is a snippet](https://imgur.com/d6bHmZS.png) of what the Infamous Alleys page looks like for me, you can see the Infamous Alley Note does just barely spill a few pixels into the 2nd column. I left that rather than edit the text, but may rethink that if page size changes don't help you. A potentially easy fix is to change 'whispered tones' to 'whispers' and you'll lose a full line and also that spill over. And shrink the transportation image to get it all to fit on one page?

Aaaaand unrelated to this pull request on my collab branch, I copied all assets into [the master branch of my git repo](https://github.com/julowe/waterdeep_dragon_heist/tree/master) (which I've been meaning to do) and then shrunk some images to get [the PDF under github's 25mb filesize limit](https://raw.githubusercontent.com/julowe/waterdeep_dragon_heist/master/Volos-Waterdeep-Enchiridion-small.pdf). This probably won't help you if you're trying to actually print this on non-letter paper, but it is a known good copy if you're just using this on tablets/latptops/etc.

**Comment by julowe** [comment]
Changed 'whispered tones' to 'whispers' in Infamous Alleys note in master and collab branches (so this pull request will render that better as well).

**Comment by cjue** [comment]
Ah yes, the Homebrewery defaulted to Page Size A4 based on my locale. 

To manually set it to letter format, I would need to add this to the style definition:
```
<style>
  .phb{
    width : 215.9mm;
    height : 279.4mm;
  }
</style>
```

Could you add that to your homebrewery markdown files?

Thanks for the update, the rendered PDF in letter format is perfect for my group. 
We already have one print version, but can't hand it around at the moment...

**Comment by julowe** [comment]
Cool, glad that fixed it! And thanks for the code, I've dropped that in to both branches now.

Also for this pull request, I've added a link in the readme and the enchiridion text itself to new updated homebrewery file I made. So you can just merge this and walk away - or update your homebrewery file with changes and keep the original link and remove my then redundant one - as you wish!

**Comment by julowe** [comment]
Created issue #2 ... because? Shrug. Maybe more visible?

**Comment by julowe** [comment]
Yeeeaaah, so I made all these edits before looking through the campaign book or anything else and didn't realize the Enchiridion was actually for sale anywhere. So go buy it: [Volo’s Waterdeep Enchiridion (5e) on DriveThruRPG](https://www.drivethrurpg.com/product/254063/Volos-Waterdeep-Enchiridion-5e)

Repo deleted and closing pull request.

**Comment by cjue** [comment]
Looks to me like the Enchiridon was only added to DriveThruRPG some time after jtbg created this repo.

**Pull request closed without merging**
